language: android
android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-25

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25

before_script:
  # Tests crash if a local.properties file isn't present; this file is not kept
  # under version control. Create an empty local.properties for testing.
- touch local.properties
